### ISSUE TITLE
次の一手を考える

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/yukarin#26]
結月ゆかり声質変換で子音が消える原因は、どうやらアライメント不足ではないらしい。
注力する方針を変更することも視野に入れつつ、次の一手を考える。

候補
* 人間の音声をターゲットにする
* 無音を省かずにアライメント
* 回帰モデルで変換した低音質音声も、高音質化学習で使う
* 多人数データをアライメント
* 多対１声質変換
* exVoiceの利用
* リアルタイムに注力

**Comment by BURI55** [comment]
論文あさりましたが、MFCCだけでは明瞭度に限界があるのでは？音素分解が必要か？Julius/Julianの活用が必要か？

**Comment by Hiroshiba** [comment]
１対１声質変換の精度を上げるのは限界なので、多対１をやってみる方針に移行する。
