### ISSUE TITLE
become-yukarinの第一段階の学習との違い

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/yukarin#60]
yukarinは、become-yukarinの第一段階学習の改良版ととらえてよろしいのでしょうか？
変更追加点は、アライメントするようになったことと、周波数の統計量を求めるようになった
ことでしょうか？

**Comment by Hiroshiba** [comment]
変更点はその２点に加えてもう１点あります。
ニューラルネットワークのモデルサイズを簡単に変えられるようにした点です。

まとめると主に次の３点の更新があります。

* データをアライメントできるようになった
* 基本周波数を線形変換できるようになった
* モデルサイズを変えられるようになった
