### ISSUE TITLE
リポジトリ修正の提案・報告

### ISSUE THREAD

**Issue by YoshikazuOota** [Hiroshiba/yukarin#61]
Twitterなどで、度々お世話になっております。  
atticです！

become-yukarin, yukarin で楽しい音声変換ライフを送らせていただいております。  
この度、yukarin リポジトリでの学習ところまで成功しましたが、いくつか修正が必要な部分がありました。

僭越ながら、オリジナルリポジトリへの修正も必要かと思い、報告させていただきます。  

#### 添付のdiffレポート
わかりやすい様に diffレポートも添付させていただきました。  
[diff_report.zip](https://github.com/Hiroshiba/yukarin/files/3310469/diff_report.zip)
(添付 diff.html : 左 -> オリジナル , 右 -> 修正案) 

**1. become_yukarin.dataset.utility の参照を yukarin.utility.align_utility  等に移動させる**  
**添付 diff.html : レポート1, レポート2**

yukarin/align_indexes.py:5 にて

```
from become_yukarin.dataset.utility import MelCepstrumAligner
```

と記載されています。
```PYTHONPATH``` の書き換えで、対応できる問題ですが、
```become_yukarin.dataset.utility``` を ```from yukarin.utility.align_utility```に移動させるのはいかがでしょうか？  

**2. readme.md の訂正**  
**添付 diff.html : レポート2**

恐れながら、下記2点は記載ミスかと思われます。
ご確認願います。

- L51 : "extract_acoustic_feature.py" -> "extract_f0_statistics.py"  
- L63 : 『,』 -> 『.』

**3. SummaryWriter が参照できないことによる train.py のエラー**  
**添付 diff.html : レポート4**

SummaryWriter はおそらく学習を可視化するなどの、補助モジュールかと思いますが、ソースコードからは発見できませんでした。  
現状、該当処理をコメントアウトして、学習ができておりますが、モジュール追加・コメントアウトなどの対応が必要かと思います。

以上、よろしくお願いいたします！

**Comment by Hiroshiba** [comment]
### 1について
`MelCepstrumAligner`は`become-yukarin`側でも用いているので、移動させることはできません。
yukarin側でアライメントを改良する予定が経てばコピーするかもしれませんが、現状はこのままが良いと思っています。

### 2について
２点とも間違いでした。ご指摘ありがとうございます。感謝しております。

### 3について
`SummaryWriter`は`tensorboard-chainer`のクラスです。
https://github.com/neka-nat/tensorboard-chainer/blob/3b46b881cd3f37a28d1c266fd78350260c00ef5a/tb_chainer/__init__.py#L4

`tensorboard-chainer`は`pip install -r requirements.txt`でインストールされるはずなので、パスが正しく通っていないのかもしれません。


ご報告とても感謝しております。
また何かあればぜひご報告頂ければと思います！

**Comment by YoshikazuOota** [comment]
ご回答ありがとうございました。
**1, 3**については、下記の2つのインストールをしていなかったのが原因でした。
ケアレスミスでお恥ずかしいです。

```
git+https://github.com/neka-nat/tensorboard-chainer
git+https://github.com/Hiroshiba/become-yukarin
```
