### ISSUE TITLE
README報告(2019/7/22)

### ISSUE THREAD

**Issue by hirotakekadowaki** [Hiroshiba/yukarin#71]
(追記)すみません。git使ってないので分かってなかったです。修正点はプルリクエストします。
→しましたのでご確認お願いします。

READMEに従い実施したところ、以下でエラーとなり、コマンドを修正したところ直りましたのでご報告いたします。

＞データを揃える（アライメントする）
＞python scripts/extract_align_indexes.py \
＞    -i1 './input_feature/*' \
(注記) target_feature/＊ がエディタで修飾されて変わってしまってます。issues投稿初めてなのでひとまずこのままにしてます。
＞    -i2 './target_feature/*' \
＞    -o './aligned_indexes/'

①エラー概要：input_feature、target_featureにnpyファイル、jsonファイルが出力されるため、extract_align_indexes.pyのコマンドでinput_feature/*を指定するとjsonファイルも読み込み込もうとしてエラーとなる。

②修正内容： input_feature/* 箇所を input_feature/*.npy とした。

③水平展開：「target_feature/*」箇所も同様となります。以下の節も同様となります。
＞周波数の統計量を求める

**Comment by Hiroshiba** [comment]
報告ありがとうございます。
現状のREADMEはミスリードになっているので、ぜひ修正したいです。
PRもありがとうございます。 #72

**Comment by Hiroshiba** [comment]
修正を反映させていただいた #73 のでこのissueは閉じます。
これに関連して何かあれば、再度openしてください。
