### ISSUE TITLE
voice_change.pyの引数--input_scaleについて

### ISSUE THREAD

**Issue by BURI55** [Hiroshiba/yukarin#78]
voice_change.pyの引数は、input_scaleで、voice_change_with_second_stage.pyの引数は、input_wave_scaleで合っていますか？どちらも1.0ですか？同じものですか？

voice_change_with_second_stage.pyでも同じようなエラーが出ましたので、input_wave_scaleに1.0を指定したところ動きましたが、voice_change.pyではinput_scaleに1.0を指定しても同じエラーが出て動きませんでした。
エラーログ
$ python yukarin/scripts/voice_change.py     --model_dir './dat/1st_models_y/yukari/1st_yukari_model_y'     --model_iteration 820000     --config_path './dat/1st_models_y/yukari/config.json'     --input_statistics 'dat/1st_models_y/yukari/statistics/own.npy'     --target_statistics 'dat/1st_models_y/yukari/statistics/target.npy'     --output_sampling_rate 24000     --test_wave_dir './dat/input'     --output_dir './dat/output' --input_scale 1.0                                 Loaded acoustic converter model "dat\1st_models_y\yukari\1st_yukari_model_y\predictor_820000.npz"
Traceback (most recent call last):
  File "yukarin/scripts/voice_change.py", line 71, in process
    w_in.wave *= input_scale
NameError: name 'input_scale' is not defined
Traceback (most recent call last):
  File "yukarin/scripts/voice_change.py", line 71, in process
    w_in.wave *= input_scale
NameError: name 'input_scale' is not defined

**Comment by Hiroshiba** [comment]
その２つの引数の意味は同じものです。

原因はわかりませんが、もしかしたらwindowsで`multiprocessing`を使うとこのエラーが発生するのかもしれません。
https://github.com/Hiroshiba/yukarin/blob/1a772240ed1070a607da57d72d8182e90315e6d7/scripts/voice_change_with_second_stage.py#L202

`--gpu`でGPU番号を指定するか、↑の行の`multiprocessing.Pool().map`を`map`に変更すると動くかもしれません。

一旦Issueは閉じますが、また何かあればコメントしてください。
