### ISSUE TITLE
Having issues with CuPy

### ISSUE THREAD

**Issue by Error404-RedRose** [Hiroshiba/yukarin#81]
I installed CUDA And CuPy with the correct versions but my system enviroment varibles is not connecting CuPy with CUDA, I dont understand what is going wrong...

**Comment by VincentThiemann** [comment]
I am having some issues with CuPy as well, however my system manages to get the two connected and running all right. What exactly is going wrong with your system? Any error messages that might be helpful?

**Comment by Error404-RedRose** [comment]
![image](https://user-images.githubusercontent.com/57733446/92988215-ee1dd300-f4a3-11ea-9573-cce4a15200e9.png)

**Comment by Error404-RedRose** [comment]
![image](https://user-images.githubusercontent.com/57733446/92988226-0beb3800-f4a4-11ea-8c63-17d8d825a2c6.png)

**Comment by Error404-RedRose** [comment]
@VincentThiemann

**Comment by Error404-RedRose** [comment]
![image](https://user-images.githubusercontent.com/57733446/92988569-3f7b9180-f4a7-11ea-80d9-d50178f061ad.png)

**Comment by Error404-RedRose** [comment]
![image](https://user-images.githubusercontent.com/57733446/92988857-d5182080-f4a9-11ea-98a2-a5327c4d4d88.png)

**Comment by Error404-RedRose** [comment]
like its there its just not reading it

**Comment by Error404-RedRose** [comment]
well more specific is the core modules are in the cupy/core

**Comment by Hiroshiba** [comment]
This issue has nothing to do with yukarin, it has to do with cupy.
Please refer to the cupy installation guide.
https://docs.cupy.dev/en/stable/install.html
